CREATE TABLE IF NOT EXISTS quizzes (id TEXT PRIMARY KEY, creator_name TEXT NOT NULL, questions TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, quiz_id TEXT NOT NULL, friend_name TEXT NOT NULL, score INTEGER NOT NULL, total INTEGER NOT NULL, tier TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_attempts_quiz ON attempts(quiz_id, score DESC);
